### ISSUE TITLE
[Simc] Missing expressions

### ISSUE THREAD

**Issue by Kutikuti** [SimCMinMax/ARParser#1]
- (active_enemies > Cache.EnemiesCount[range]  (ie : T21_Priest_Shadow.lua))
- (spell_targets.X > Cache.EnemiesCount[range]  (ie : T21_Death_Knight_Blood.lua))
- charges_fractional > S.X:ChargesFractionalP() (ie : T21_Shaman_Enhancement.lua)
- artifact.X.rank > S.X:ArtifactRank() (ie : T21_Priest_Shadow.lua)
- insanity > Player:Insanity() (ie : T21_Priest_Shadow.lua)
- maelstrom (ie : T21_Shaman_Enhancement.lua)
- ticking (ie : T21_Priest_Shadow.lua) (not yet implemented in aethysrotation)
- level > Player:Level() (ie : T21_Shaman_Enhancement.lua)
- energy > Player:Energy() (ie : T21_Druid_Feral.lua)
- energy.regen > Player:EnergyRegen() (ie : T21_Druid_Feral.lua)
- combo_points > Player:ComboPoints() (ie : T21_Druid_Feral.lua)
- max_charges > S.X:MaxCharges() (ie : T21_Druid_Feral.lua)
- time_to_die > Target:TimeToDie (the no "target." version) (ie : T21_Druid_Feral.lua)

- all Class\Unit\Player\Power.lua

tbc ...

**Comment by skasch** [comment]
Done:

* spell_targets
* charges_fractional
* ticking

**Comment by skasch** [comment]
What should be the range for active_enemies? @Kutikuti 
Otherwise, done:

* artifact.spell.rank/enabled
* all resources
* level
* ticking (alone)
* max_charges
* time_to_die

Should be all good except active_enemies and some specific resources methods.

**Comment by Kutikuti** [comment]
Depends on the class. What i do on my rotations is define a locale range = X and then call Cache.EnemiesCount[range] everywhere it needs to(except for specific ranges). But most spells of a spec have the same range. You can look at sp/balance/warlocks from aer

**Comment by skasch** [comment]
Done with active_enemies for all classes. Some ranges might be missing, but the core is working.
