### ISSUE TITLE
[Simc] Missing expressions

### ISSUE THREAD

**Issue by Kutikuti** [SimCMinMax/ARParser#3]
- [x] rage > Player:Rage()    / rage.max > Player:RageMax()  /  rage.deficit > Player:RageDeficit() (T21_warrior_fury.simc, T21_warrior_arms.simc)
- [x] prev_off_gcd.x > Player:PrevOffGCDP(1, S.X) (T21_warrior_fury.simc)
- [x] target.debuff.X.remains > Target:DebuffRemainsP(S.X) (T21_warrior_arms.simc)
- [x] soul_shard > Player:SoulShards() but there is a function that overrides it in warlocks rotation : FutureShard()
- [x] energy.time_to_max > Player:EnergyTimeToMax () or Player:EnergyTimeToMaxPredicted ()
- [x] target.debuff.casting.react > Target:IsCasting()

**Comment by skasch** [comment]
Done:

* Rage
* prev_off_gcd
* target.debuff.X.remains, target.debuff.casting(.react)
* resource.time_to_max

To do:

* soul_shard specific function for warlocks

**Comment by skasch** [comment]
Added soul_shard > FutureShard.
