### ISSUE TITLE
[Deathknight] wrong parsing for runes

### ISSUE THREAD

**Issue by FluffyDK** [SimCMinMax/ARParser#4]
if you have in your APL:
```-- obliterate,if=runic_power.deficit>25|rune>3```
will generate:
```lua
    if S.Obliterate:IsCastableP() and (Player:RunicPowerDeficit() > 25 or Player:Rune() > 3) then
      if HR.Cast(S.Obliterate) then return ""; end
    end
```
must be:
```Player:Runes()```

**Comment by Kutikuti** [comment]
Updated HeroRotation to Player:Rune() instead of Player:Runes() so it match simc usage : 
https://github.com/herotc/hero-lib/commit/b6c88910725bb2c8dcaba6b23fb171de5087d5b1
